version: '3'

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-15
    networks:
     - socarotte-postgres
    volumes:
     - 'socarotte-postgres-data:/var/lib/postgresql/data:rw'
    environment:
     - POSTGRES_PASSWORD=sigl2024
     - POSTGRES_USER=sigl2024
    ports:
    - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4:7.1
    container_name: pgadmin4
    networks:
     - socarotte-postgres
    volumes:
     - 'socarotte-pgadmin-data:/var/lib/pgadmin:rw'
    environment:
     - PGADMIN_DEFAULT_EMAIL=socra@sigl.fr
     - PGADMIN_DEFAULT_PASSWORD=sigl2024
    ports:
     - '8040:80'

networks:
  socarotte-postgres:
    name: socarotte-postgres

volumes: 
    socarotte-postgres-data:
    socarotte-pgadmin-data:
