version: '3'

services:
  mongodb:
    image: mongo:5
    container_name: mongo-5
    volumes:
    - 'socarotte-mongo-data:/data/db'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=sigl2024
    - MONGO_INITDB_ROOT_PASSWORD=sigl2024
    ports:
    - '27017:27017'

volumes: 
  socarotte-mongo-data: